// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package report_test is a generated GoMock package.
package report_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	report "github.com/maypok86/payment-api/internal/domain/report"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetReportContent mocks base method.
func (m *MockService) GetReportContent(ctx context.Context, filename string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportContent", ctx, filename)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportContent indicates an expected call of GetReportContent.
func (mr *MockServiceMockRecorder) GetReportContent(ctx, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportContent", reflect.TypeOf((*MockService)(nil).GetReportContent), ctx, filename)
}

// GetReportKey mocks base method.
func (m *MockService) GetReportKey(ctx context.Context, dto report.GetMapDTO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReportKey", ctx, dto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReportKey indicates an expected call of GetReportKey.
func (mr *MockServiceMockRecorder) GetReportKey(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReportKey", reflect.TypeOf((*MockService)(nil).GetReportKey), ctx, dto)
}
