name: Lint

on:
  push:
    branches-ignore:
      - release

jobs:
  lint:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=4m -v