name: Test

on:
  push:
    branches-ignore:
      - release

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Unit tests
        run: make test.unit

      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash)